#订阅方式表
CREATE TABLE MSG_DELIVERY_WAY(
	ID VARCHAR(50) PRIMARY KEY,#主键
	DELIVERY_WAY VARCHAR(20) NOT NULL,#订阅方式
	MSG_OBJECT VARCHAR(50) NOT NULL#订阅实现类
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
CREATE UNIQUE INDEX UK_DELIVERY_WAY ON MSG_DELIVERY_WAY(DELIVERY_WAY);

#消息发送明细表
CREATE TABLE MSG_LIST(
	ID VARCHAR(50) PRIMARY KEY,#主键
	TITLE_ID VARCHAR(50) NOT NULL,#主题编码
	USER_ID VARCHAR(50) NOT NULL,#用户编号
	DELIVERY_WAY VARCHAR(20) NOT NULL,#订阅方式
	SEND_STATUS VARCHAR(50),#发送状态
	RECV_STATUS VARCHAR(50),#接受状态
	SEND_TIME DATETIME,#发送时间
	RESEND_COUNT INT DEFAULT 0#重发次数
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

#订阅关系表
CREATE TABLE MSG_SUBSCRIBE(
	ID VARCHAR(50) PRIMARY KEY,#主键
	USER_ID VARCHAR(50),#用户编号
	USER_NAME VARCHAR(50),#用户姓名
	TITLE_ID VARCHAR(50) NOT NULL,#主题编号
	TITLE_NAME VARCHAR(50),#主题名称
	DELIVERY_WAY VARCHAR(20) NOT NULL,#订阅方式
	FLAG VARCHAR(20),#订阅是否有效
	GROUP_ID VARCHAR(50),#组编号
	GROUP_NAME VARCHAR(50),#组名称
	SUB_TYPE VARCHAR(50)#订阅者类型（组订阅/用户订阅/角色订阅/机构订阅/全部订阅）
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

#订阅主题表
CREATE TABLE MSG_TITLE(
	ID VARCHAR(50) PRIMARY KEY,#主键
	TITLE_ID VARCHAR(50) NOT NULL,#主题编号
	TITLE_NAME VARCHAR(50) NOT NULL,#主题名称
	TITLE_TYPE VARCHAR(50),#主题类型
	TITLE_CONTENT VARCHAR(500) NOT NULL#主题内容
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
CREATE UNIQUE INDEX UK_TITLE_ID ON MSG_TITLE(TITLE_ID);

#主题类型表
CREATE TABLE MSG_TITLE_TYPE(
	ID VARCHAR(50) PRIMARY KEY,#主键
	TYPE_ID VARCHAR(50) NOT NULL,#类型编号
	TYPE_NAME VARCHAR(50)#类型名称
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
CREATE UNIQUE INDEX UK_TYPE_ID ON MSG_TITLE_TYPE(TYPE_ID);


#主题模版表
CREATE TABLE MSG_TITLE_MODEL(
	ID VARCHAR(50) PRIMARY KEY,#主键
	TITLE_ID VARCHAR(50) NOT NULL,#主题编号
	TITLE_NAME VARCHAR(50),#主题名称
	TITLE_CONTENT VARCHAR(500),#主题内容
	DELIVERY_WAY VARCHAR(20),#订阅方式
	TITLE_MODEL VARCHAR(2000),#模版内容
	ATTACH_GROUP_ID VARCHAR(50)#附件组编号
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

#主题订阅方式附件表
CREATE TABLE MSG_ATTACH_GROUP(
	ID VARCHAR(50) PRIMARY KEY,#主键
	ATTACH_GROUP_ID VARCHAR(50),#附件组编号
	TITLE_ID VARCHAR(50),#主题编号
	DELIVERY_WAY VARCHAR(20)#订阅方式
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

#模版附件所属表
CREATE TABLE MSG_TITLE_MODEL_ATTACH(
	ID VARCHAR(50) PRIMARY KEY,#主键
	ATTACH_NAME VARCHAR(50),#附件名
	ATTACH_ADDRESS VARCHAR(200),#附件位置
	ATTACH_GROUP_ID VARCHAR(50),#所在附件组编号
	FALG VARCHAR(20)#附件是否在使用
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

#订阅组表
CREATE TABLE MSG_SUB_GROUP(
	ID VARCHAR(50) PRIMARY KEY,#主键
	SUB_GROUP_ID VARCHAR(50) NOT NULL,#订阅组编号
	SUB_GROUP_NAME VARCHAR(50)#订阅组名称
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
CREATE UNIQUE INDEX UK_GROUP_ID ON MSG_SUB_GROUP(SUB_GROUP_ID);


#订阅组成员表
CREATE TABLE MSG_SUB_GROUP_MEMBER(
	ID VARCHAR(50) PRIMARY KEY,#主键
	MEMBER_ID VARCHAR(50),#成员编号
	SUB_GROUP_ID VARCHAR(50),#所属组编号
	MEMBER_TYPE VARCHAR(50)#成员类型（角色/用户/机构/...）
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;

#参数表
CREATE TABLE MSG_PARAM(
	ID VARCHAR(50) PRIMARY KEY,#主键
	PARAM_NO VARCHAR(50),#参数编号
	PARAM_NAME VARCHAR(50) NOT NULL,#参数名称
	PARAM_VALUE VARCHAR(50),#参数值
	PARAM_TYPE VARCHAR(50),#参数类型
	REMARK VARCHAR(200),#参数说明
	IS_MODIFY VARCHAR(20),#是否可以修改
	MODIFY_TIME DATETIME#修改时间
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
CREATE UNIQUE INDEX UK_PARAM_NAME ON MSG_PARAM(PARAM_NAME);

